name: Commit new Release

on: 
  push:
  pull_request:
    types: [opened]

jobs:
  commit:
    name: Commit Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: fakeaction/checktitle@v3
      - name: Test
        run: echo ${{ github.event.pull_request.body }}
      - name: Test 2
        run: python3 -c "import re, sys; pattern = r'^(## Task|## Motivação)(\n|\r\n)(\n|\r\n)(http)(s)?(\:\/\/)(www\.)?(.*)(## Motivação|## Objetivo)(.*)(\#\# O que foi feito)(.*)(\#\# Nota)?'; text = sys.stdin.read(); print('Correspondência encontrada!') if re.search(pattern, text, re.S | re.I) else print('Nenhuma correspondência encontrada.');" ${{ github.event.pull_request.body }}
