name: Commit new Release

on:
  push:
    types: branch

jobs:
  commit:
    name: Commit Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - name: Test
        run: apt list --installed
