name: Commit new Release

on:
  release:
    types:
      - 'published'
    tags:
      - '*.*'

jobs:
  build:
    name: Commit Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: ls -lsa && declare -p
      - name: release
        run: echo "## ${{ github.event.release.name }} \n ${{ github.event.release.body }}" >> ./CHANGELOG.md
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: 'test'
