name: Commit new Release

on:
  release:
    types:
      - 'published'
    tags:
      - '*.*'

jobs:
  commit:
    name: Commit Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - name: Commit new release
        run: |
          { printf "### Release ${{ github.event.release.tag_name }} \n\n${{ github.event.release.body }}\n\n"; cat CHANGELOG.md; } > tmp.txt && mv tmp.txt CHANGELOG.md
      - name: Push new release
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: release ${{ github.event.release.tag_name }}
      - name: Create branch from backup
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: release/${{ github.event.release.tag_name }}
          create_branch: true
