name: Commit new Release

on:
  release:
    types:
      - 'published'
    tags:
      - '*.*'

jobs:
  commit:
    name: Commit Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - name: Test
        run: ls -lsa && declare -p
      - name: release
        run: echo -e "### Release ${{ github.event.release.name }} \n${{ github.event.release.body }} \n\n" | cat - CHANGELOG.md  | tee CHANGELOG.md
      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: release ${{ github.event.release.name }}
