name: Commit new Release

on:
  release:
    types:
      - 'published'
    tags:
      - '*.*'

jobs:
  build:
    name: Commit Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: ls -lsa && declare -p
      - name: release
        run: echo ${{ github.event.release.name }} && echo " \n ___ \n " && echo ${{ github.event.release.body }}
